### ISSUE TITLE
Settings for Columns

### ISSUE THREAD

**Issue by msmedien** [pattihis/simple-photo-feed#2]
Hi, first of all, the Plugin is pretty simple and awesome at the same time! :)

Is there an solution for more columns? If i set up the plugin it shows the Feed always in 3 columns... But i need 4 or 5 columns. :-/ Can i manage it in the shortcode or is an option for this planned?

Thanks for your help and answer! :-)

**Comment by pattihis** [comment]
Hi @msmedien , I tried to keep it as simple as possible with minimal styles so that people can easily customize it. There is however the option for more columns if you use the `size="small"` attribute in the shortcode. Let me know if it works for you, thanks!

**Comment by msmedien** [comment]
Hi @pattihis, thanks for your answer. If i use `size="small"` i got 5 columns, BUT the photos aren't squared anymore... The photos become a format like 5:4 landscaped (or so). This is for the photos not a good solutions. The most Instagram photos are squared or 4:5 portraited.

**Comment by pattihis** [comment]
Yes, as I said you can customize that. Please give me a public URL where I can see it with the 5 columns, and I will give you a small CSS snippet to adjust the aspect-ratio.

**Comment by pattihis** [comment]
Yes, as I said you can customize that. If nothing in your theme/plugins affects it, this will do:

```
.spf_container.spf_size_small .spf_item {
  padding-bottom: 100%!important;
}
```

It will show your images square when using the `size='small'`. To add custom CSS to your WP site you can go to 
`Appearance → Customize → Additional CSS`

I will be adding more layout options in future versions. Thanks!

**Comment by msmedien** [comment]
Thanks for your hint! :-)

I found another solution that works well for me.

> .spf_container {
>     width: 100%;
>     display: grid;
>     grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
>     gap: 0.5rem;
>     padding: 1rem;
>     white-space: normal;
> }

I just added two `1fr` to the `grid-template-columns` in css. :-) More easy then i thought. Thanks for the hint with the custom css. Maybe would a simple dropdown menu in the plugin settings nice to select the number of columns. :-)

**Comment by pattihis** [comment]
Awesome. Glad you figured it out. I will be improving it more in the future, thanks!
